import type React from 'react'

export const voteStyles: Record<string, React.CSSProperties> = {
  container: {
    margin: 'var(--spacing-8) 0',
    padding: 'var(--spacing-6)',
    borderRadius: 'var(--radius-xlarge)',
    border: '3px solid var(--neutral-black)',
    backgroundColor: 'var(--neutral-white)',
    boxShadow: 'var(--shadow-level-2)',
    transition: 'transform var(--transition-normal) ease',
  },
  header: {
    marginBottom: 'var(--spacing-6)',
    textAlign: 'center',
    padding: 'var(--spacing-3) var(--spacing-5)',
    backgroundColor: 'var(--accent-yellow)',
    borderRadius: 'var(--radius-large)',
    margin: 'var(--spacing-4)',
  },
  title: {
    fontSize: '1.5rem',
    fontWeight: 'var(--font-weight-semibold)',
    margin: '0 0 var(--spacing-1) 0',
    color: 'var(--neutral-900)',
  },
  subtitle: {
    fontSize: '0.95rem',
    color: 'var(--neutral-600)',
    margin: 0,
  },
  notConnected: {
    textAlign: 'center',
    padding: 'var(--spacing-8)',
    backgroundColor: 'var(--accent-yellow-light)',
    border: '1px solid var(--accent-yellow-dark)',
    borderRadius: 'var(--radius-medium)',
    color: 'var(--accent-yellow-text)',
  },
  walletInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--spacing-1)',
    padding: 'var(--spacing-2) var(--spacing-4)',
    backgroundColor: 'var(--primary-blue-light)',
    border: '2px solid var(--primary-blue)',
    borderRadius: 'var(--radius-medium)',
    marginBottom: 'var(--spacing-6)',
    flexWrap: 'wrap',
  },
  walletLabel: {
    fontSize: '0.875rem',
    color: 'var(--neutral-700)',
    fontWeight: 'var(--font-weight-semibold)',
  },
  walletAddress: {
    fontSize: '0.875rem',
    padding: '0.25rem 0.5rem',
    backgroundColor: 'var(--neutral-white)',
    border: '2px solid var(--primary-blue)',
    borderRadius: 'var(--radius-small)',
    fontFamily: 'Consolas, Monaco, monospace',
    color: 'var(--primary-blue)',
  },
  warningBadge: {
    fontSize: '0.75rem',
    color: 'var(--accent-yellow-text)',
    marginLeft: 'auto',
    fontWeight: 'var(--font-weight-semibold)',
  },
  proposalTitle: {
    padding: 'var(--spacing-4)',
    marginBottom: 'var(--spacing-5)',
    backgroundColor: 'var(--accent-purple-light)',
    border: '2px solid var(--accent-purple)',
    borderRadius: 'var(--radius-large)',
    fontSize: '1rem',
    fontWeight: 'var(--font-weight-semibold)',
    color: 'var(--neutral-900)',
  },
  section: {
    marginBottom: 'var(--spacing-5)',
  },
  optionsSection: {
    marginBottom: 'var(--spacing-5)',
  },
  label: {
    display: 'block',
    fontSize: '1rem',
    fontWeight: 'var(--font-weight-semibold)',
    marginBottom: 'var(--spacing-2)',
    color: 'var(--neutral-900)',
  },
  optionList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--spacing-3)',
    listStyle: 'none',
    padding: 0,
    margin: 0,
  },
  loading: {
    color: 'var(--neutral-500)',
    fontStyle: 'italic',
    textAlign: 'center',
  },
  empty: {
    color: 'var(--neutral-500)',
    textAlign: 'center',
  },
  optionCard: {
    padding: 'var(--spacing-4)',
    borderRadius: 'var(--radius-large)',
    border: '3px solid var(--neutral-200)',
    backgroundColor: 'var(--neutral-25)',
    cursor: 'pointer',
    transition: 'all var(--transition-normal) ease',
  },
  optionCardSelected: {
    border: '3px solid var(--primary-blue)',
    backgroundColor: 'var(--primary-blue-light)',
    transform: 'translateY(-2px)',
    boxShadow: 'var(--shadow-level-2)',
  },
  optionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 'var(--spacing-2)',
  },
  radioContainer: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 'var(--spacing-3)',
    flex: 1,
    minWidth: 0,
  },
  radio: {
    width: '20px',
    height: '20px',
    minWidth: '20px',
    minHeight: '20px',
    borderRadius: '50%',
    border: '3px solid var(--neutral-300)',
    transition: 'all var(--transition-normal) ease',
    flexShrink: 0,
  },
  radioSelected: {
    border: '3px solid var(--primary-blue)',
    backgroundColor: 'var(--primary-blue)',
    boxShadow: 'inset 0 0 0 3px white',
  },
  optionName: {
    fontSize: '1rem',
    fontWeight: 'var(--font-weight-semibold)',
    color: 'var(--neutral-900)',
    wordBreak: 'break-word',
  },
  optionMeta: {
    fontSize: '0.85rem',
    color: 'var(--neutral-500)',
    marginTop: '0.35rem',
  },
  voteCount: {
    fontSize: '0.875rem',
    color: 'var(--neutral-500)',
    fontWeight: 'var(--font-weight-semibold)',
    flexShrink: 0,
    marginLeft: 'var(--spacing-2)',
  },
  progressBar: {
    display: 'none',
  },
  progressFill: {
    display: 'none',
  },
  voteButton: {
    width: '100%',
    padding: 'var(--spacing-3) var(--spacing-10)',
    fontSize: '1.1rem',
    fontWeight: 'var(--font-weight-semibold)',
    color: 'var(--neutral-black)',
    backgroundColor: 'var(--accent-yellow)',
    border: '3px solid var(--neutral-black)',
    borderRadius: 'var(--radius-pill)',
    cursor: 'pointer',
    transition: 'all var(--transition-normal) ease',
    boxShadow: 'var(--shadow-bottom-4)',
  },
  voteButtonDisabled: {
    backgroundColor: 'var(--neutral-200)',
    color: 'var(--neutral-400)',
    border: '3px solid var(--neutral-300)',
    cursor: 'not-allowed',
    boxShadow: 'none',
  },
  errorMessage: {
    marginTop: 'var(--spacing-4)',
    padding: 'var(--spacing-2) var(--spacing-4)',
    backgroundColor: 'var(--accent-yellow-light)',
    border: '2px solid var(--accent-yellow-dark)',
    color: '#dc2626',
    borderRadius: 'var(--radius-medium)',
    fontSize: '0.875rem',
    fontWeight: 'var(--font-weight-semibold)',
  },
  privacyNotice: {
    marginTop: 'var(--spacing-6)',
    padding: 'var(--spacing-4)',
    backgroundColor: 'var(--accent-yellow-light)',
    borderTop: '2px solid var(--accent-yellow-dark)',
    borderRight: '2px solid var(--accent-yellow-dark)',
    borderBottom: '2px solid var(--accent-yellow-dark)',
    borderLeft: '4px solid var(--accent-yellow-dark)',
    borderRadius: 'var(--radius-large)',
    fontSize: '0.875rem',
    lineHeight: 'var(--line-height-relaxed)',
    color: 'var(--neutral-700)',
  },
  txDetailContainer: {
    marginTop: 'var(--spacing-6)',
  },
  successHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--spacing-2)',
    fontSize: '1.1rem',
    fontWeight: 'var(--font-weight-semibold)',
    color: '#16a34a',
    marginBottom: 'var(--spacing-4)',
  },
  successIcon: {
    fontSize: '1.25rem',
  },
  txCard: {
    padding: 'var(--spacing-4)',
    backgroundColor: 'var(--neutral-25)',
    border: '3px solid var(--neutral-black)',
    borderRadius: 'var(--radius-large)',
    marginBottom: 'var(--spacing-4)',
    boxShadow: 'var(--shadow-level-2)',
  },
  txCardTitle: {
    margin: '0 0 var(--spacing-4) 0',
    fontSize: '1rem',
    fontWeight: 'var(--font-weight-semibold)',
    color: 'var(--neutral-900)',
  },
  txRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--spacing-1)',
    marginBottom: 'var(--spacing-3)',
    paddingBottom: 'var(--spacing-3)',
    borderBottom: '1px dashed var(--neutral-200)',
  },
  txLabel: {
    fontSize: '0.85rem',
    color: 'var(--neutral-600)',
    fontWeight: 'var(--font-weight-semibold)',
  },
  txValue: {
    fontSize: '0.75rem',
    fontFamily: 'Consolas, Monaco, monospace',
    backgroundColor: 'var(--neutral-100)',
    padding: 'var(--spacing-2)',
    borderRadius: 'var(--radius-small)',
    wordBreak: 'break-all',
    color: 'var(--neutral-700)',
    border: '1px solid var(--neutral-200)',
  },
  txValueHighlight: {
    fontSize: '0.75rem',
    fontFamily: 'Consolas, Monaco, monospace',
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    padding: 'var(--spacing-2)',
    borderRadius: 'var(--radius-small)',
    wordBreak: 'break-all',
    color: '#dc2626',
    border: '2px solid #dc2626',
  },
  txValueSmall: {
    fontSize: '0.7rem',
    fontFamily: 'Consolas, Monaco, monospace',
    backgroundColor: 'var(--neutral-100)',
    padding: 'var(--spacing-2)',
    borderRadius: 'var(--radius-small)',
    wordBreak: 'break-all',
    color: 'var(--neutral-600)',
    border: '1px solid var(--neutral-200)',
  },
  explorerLink: {
    display: 'inline-block',
    marginTop: 'var(--spacing-2)',
    color: 'var(--primary-blue)',
    textDecoration: 'none',
    fontSize: '0.875rem',
    fontWeight: 'var(--font-weight-semibold)',
    transition: 'color var(--transition-normal) ease',
  },
  inputDataAnalysis: {
    padding: 'var(--spacing-4)',
    backgroundColor: 'var(--primary-blue-light)',
    border: '2px solid var(--primary-blue)',
    borderRadius: 'var(--radius-large)',
    marginBottom: 'var(--spacing-4)',
  },
  analysisTitle: {
    margin: '0 0 var(--spacing-3) 0',
    fontSize: '1rem',
    fontWeight: 'var(--font-weight-semibold)',
    color: 'var(--neutral-900)',
  },
  analysisText: {
    fontSize: '0.875rem',
    color: 'var(--neutral-600)',
    margin: '0 0 var(--spacing-3) 0',
    lineHeight: 'var(--line-height-relaxed)',
  },
  dataBreakdown: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--spacing-2)',
  },
  dataItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--spacing-3)',
    flexWrap: 'wrap',
  },
  dataSelector: {
    fontSize: '0.8rem',
    fontFamily: 'Consolas, Monaco, monospace',
    backgroundColor: 'var(--primary-blue)',
    color: 'var(--neutral-white)',
    padding: '0.25rem 0.5rem',
    borderRadius: 'var(--radius-small)',
    fontWeight: 'var(--font-weight-semibold)',
  },
  dataParam: {
    fontSize: '0.8rem',
    fontFamily: 'Consolas, Monaco, monospace',
    backgroundColor: 'var(--accent-yellow)',
    color: 'var(--neutral-black)',
    padding: '0.25rem 0.5rem',
    borderRadius: 'var(--radius-small)',
    fontWeight: 'var(--font-weight-semibold)',
  },
  dataExplain: {
    fontSize: '0.85rem',
    color: 'var(--neutral-600)',
  },
  privacyAlert: {
    padding: 'var(--spacing-4)',
    backgroundColor: 'var(--accent-orange-light)',
    border: '3px solid var(--accent-orange)',
    borderRadius: 'var(--radius-large)',
    borderLeft: '4px solid var(--accent-orange)',
    boxShadow: 'var(--shadow-level-1)',
  },
  alertTitle: {
    margin: '0 0 var(--spacing-3) 0',
    fontSize: '1rem',
    fontWeight: 'var(--font-weight-semibold)',
    color: '#dc2626',
  },
  alertText: {
    fontSize: '0.875rem',
    color: 'var(--neutral-700)',
    margin: '0 0 var(--spacing-2) 0',
    lineHeight: 'var(--line-height-relaxed)',
  },
  alertList: {
    margin: '0 0 var(--spacing-4) 0',
    paddingLeft: 'var(--spacing-5)',
    fontSize: '0.85rem',
    lineHeight: 'var(--line-height-relaxed)',
    color: 'var(--neutral-700)',
    textAlign: 'left',
  },
  alertConclusion: {
    fontSize: '0.9rem',
    color: 'var(--neutral-900)',
    margin: 0,
    padding: 'var(--spacing-3)',
    backgroundColor: 'var(--accent-yellow-light)',
    border: '2px solid var(--accent-yellow-dark)',
    borderRadius: 'var(--radius-medium)',
    fontWeight: 'var(--font-weight-semibold)',
  },
  primaryButton: {
    padding: '0.5rem 1rem',
    backgroundColor: '#2563eb',
    color: '#fff',
    border: 'none',
    borderRadius: 'var(--radius-medium)',
    cursor: 'pointer',
    fontWeight: 600,
  },
  secondaryButton: {
    padding: '0.5rem 1rem',
    backgroundColor: '#fff',
    color: '#0f172a',
    border: '1px solid var(--neutral-300)',
    borderRadius: 'var(--radius-medium)',
    cursor: 'pointer',
    fontWeight: 600,
  },
}
